addSbtPlugin("com.eed3si9n"              % "sbt-assembly"  % "0.15.0")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo" % "0.9.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"  % "2.4.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"  % "0.1.16")
addSbtPlugin("org.foundweekends"         % "sbt-bintray"   % "0.5.6")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"  % "0.9.24")
