addSbtPlugin("com.eed3si9n"              % "sbt-assembly"  % "1.1.0")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo" % "0.9.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"  % "2.4.5")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"  % "0.1.20")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"  % "0.9.33")
