name: ci

on: [push, pull_request]

jobs:
  test:
    name: Compile & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Install Java and sbt
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8
      - name: Restore sbt cache
        uses: coursier/cache-action@v6
      - name: Compile and run tests
        run: sbt test
        env:
          SNOWPLOW_API_CLIENT_ID: ${{ secrets.SNOWPLOW_API_CLIENT_ID }}
          SNOWPLOW_API_CLIENT_SECRET: ${{ secrets.SNOWPLOW_API_CLIENT_SECRET }}