name: release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Install Java and sbt
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8
      - name: Restore sbt cache
        uses: coursier/cache-action@v6
      - name: Assembly
        run: sbt assembly
        env:
          SNOWPLOW_API_CLIENT_ID: ${{ secrets.SNOWPLOW_API_CLIENT_ID }}
          SNOWPLOW_API_CLIENT_SECRET: ${{ secrets.SNOWPLOW_API_CLIENT_SECRET }}
      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Zip artifact
        run: zip -qq -j 'data_structures_ci_${{ env.VERSION }}.zip' target/data-structures-ci
      - name: Release
        uses: softprops/action-gh-release@master
        with:
          name: v${{ env.VERSION }}
          files: '*.zip'
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
